// Synthetic page-level contract test; never connects to a browser or network.
"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const path = require("node:path");

const jsPath = path.join(
  __dirname, "..", "src", "chatgpt_web_adapter",
  "browser_native_extension", "service_worker_capability_capture_v0.js"
);
const worker = vm.createContext({});
vm.runInContext(fs.readFileSync(jsPath, "utf8"), worker);

class Element {
  getBoundingClientRect() { return { width: 100, height: 30, left: 0 }; }
  contains(other) { return this === other; }
}
class HTMLTextAreaElement extends Element {
  constructor() { super(); this.value = ""; }
}
const source = new HTMLTextAreaElement();
const output = new Element();
output.textContent = "";
const listeners = new Map();
const document = {
  querySelectorAll(selector) {
    if (selector.startsWith("textarea")) return [source];
    if (selector.startsWith("[jsname")) return [output];
    throw new Error("Unexpected selector");
  },
  addEventListener(type, listener) {
    if (type !== "input") throw new Error("Unexpected listener");
    listeners.set(type, listener);
  },
  removeEventListener(type, listener) {
    if (listeners.get(type) === listener) listeners.delete(type);
  }
};
const page = vm.createContext({
  window: {},
  document,
  Element,
  HTMLTextAreaElement,
  getComputedStyle: () => ({ display: "block", visibility: "visible" }),
  location: { href: "https://translate.google.com/?sl=en&tl=es&op=translate" },
  URL
});

function evaluate(mode) {
  const expression = worker._cwaCaptureV0PageExpression(mode);
  return vm.runInContext(expression, page);
}

const installed = evaluate("install");
assert.equal(installed.ready, true);
assert.equal(listeners.has("input"), true);

let observation = evaluate("observe");
assert.equal(observation.inputEvents, 0);
assert.equal(observation.candidateCount, 0);

// The user's demonstration is simulated by one page-owned input event.
// The observer does not send this input and must never export its contents.
source.value = "super private demonstration input";
listeners.get("input")({ target: source });
output.textContent = "private translated output";
observation = evaluate("observe");
assert.equal(observation.inputEvents, 1);
assert.equal(observation.candidateCount, 1);
assert.equal(observation.candidateIdentityResolved, true);
assert.equal(observation.sourceRoute, "en");
assert.equal(observation.targetRoute, "es");
const serialized = JSON.stringify(observation);
assert.equal(serialized.includes("super private"), false);
assert.equal(serialized.includes("private translated"), false);

const removed = evaluate("remove");
assert.equal(removed.removed, true);
assert.equal(listeners.has("input"), false);
assert.equal(evaluate("observe").ready, false);
// Exercise the real observational worker function against a fully fake CDP
// and page. The event below is generated by the synthetic human, not the worker.
let clock = 0;
let injectHumanEvent = true;
let detachFailures = false;
let detachCount = 0;

worker.chrome = {
  tabs: {
    get: async (id) => ({
      id,
      url: "https://translate.google.com/?sl=en&tl=es&op=translate"
    })
  },
  debugger: {
    attach: async () => {},
    detach: async () => {
      detachCount++;
      if (detachFailures) throw new Error("SIMULATED_DETACH_FAILURE");
    }
  }
};
worker.CDP_PROTOCOL_VERSION = "1.3";
worker.performance = { now: () => (clock += 160) };
worker.sleep = async () => {};
worker.URL = URL;
worker._cwaBaseSendCommand = async (_debuggee, command, args) => {
  if (command === "Runtime.enable") return {};
  assert.equal(command, "Runtime.evaluate");
  if (args.expression.includes("const state=window[key];if(!state") && injectHumanEvent) {
    source.value = "private input for the synthetic human";
    listeners.get("input")({ target: source });
    output.textContent = "private translated output";
    injectHumanEvent = false;
  }
  return { result: { value: vm.runInContext(args.expression, page) } };
};

async function testWorker() {
  source.value = "";
  output.textContent = "";
  const request = {
    tabId: 27, captureSeconds: 5,
    sourceLanguage: "en", targetLanguage: "es",
    consent: "EXPLICIT_OBSERVE_ONLY"
  };
  const result = await worker._cwaCaptureV0ObserveTranslate(request);
  assert.equal(result.candidatePresenceStable, true);
  assert.equal(result.semanticFinalityProven, false);
  assert.equal(result.canonicalCompletionProven, false);
  assert.equal(result.automaticRetry, false);
  assert.equal(result.replayExecutable, false);
  assert.equal(result.rawContentRetained, false);
  assert.deepEqual(Array.from(result.events, e => e.phase), [
    "source_ready", "source_input_event",
    "result_candidate_seen", "result_candidate_presence_stable"
  ]);
  assert.equal(listeners.has("input"), false);
  assert.equal(detachCount, 1);
  assert.equal(JSON.stringify(result).includes("private input"), false);
  assert.equal(JSON.stringify(result).includes("private translated"), false);

  source.value = "";
  output.textContent = "";
  injectHumanEvent = true;
  detachFailures = true;
  await assert.rejects(
    () => worker._cwaCaptureV0ObserveTranslate(request),
    /CAPTURE_V0_CLEANUP_UNPROVEN/
  );
  assert.equal(listeners.has("input"), false);
  assert.equal(detachCount, 2);
  process.stdout.write("CAPTURE_V0_DOM_FIXTURE_OK\\n");
}
testWorker().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
